version: 2

sources:
  - name: gz_raw_data
    database: strange-radius-465210-n5   # <- your GCP project_id
    schema: gz_raw_data
    tables:
      - name: raw_gz_sales
      - name: raw_gz_product
      - name: raw_gz_ship